[package]
name = "dijag/test123"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Vide = "alicesaidhi/vide@0.4.0"
Networker = "lcarpet/networker@0.1.1"
Dataservice = "leifstout/dataservice@1.0.0"

[server-dependencies]
